#!/usr/bin/env python3
"""
build_static.py — Refresh the inline blocks inside app/index.html with the
current style.css, data.js and app.js. Run this whenever you edit those files
and want to commit a self-contained index.html (required for Onslate static
hosting, where external CSS/JS is blocked).

Run from project root:
    python tools/build_static.py

The running Flask server (python app/server.py) also inlines these files on
the fly, so this script is only needed to produce a deployable static artifact.
"""
import os
import re

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP = os.path.join(BASE, "app")


def read(p):
    with open(os.path.join(APP, p), "r", encoding="utf-8") as f:
        return f.read()


def main():
    html = read("index.html")
    css = read("style.css")
    js = read("app.js")
    data = read("data.js")

    # Callable replacements so characters like \w in app.js are NOT treated as
    # regex group escapes in the replacement string.
    html = re.sub(r"<style>.*?</style>", lambda m: f"<style>{css}</style>", html,
                  count=1, flags=re.S)
    html = re.sub(r"<script>\s*/\* Auto-generated by tools/gen_data\.py.*?</script>",
                  lambda m: f"<script>{data}</script>", html, count=1, flags=re.S)
    html = re.sub(r"<script>\s*/\* =+\s*\n\s*NEX-CODE-SRIKERS · Frontend logic.*?</script>",
                  lambda m: f"<script>{js}</script>", html, count=1, flags=re.S)

    with open(os.path.join(APP, "index.html"), "w", encoding="utf-8") as f:
        f.write(html)

    print("Refreshed app/index.html inline blocks (style.css + data.js + app.js).")


if __name__ == "__main__":
    main()
