#!/usr/bin/env python3
"""
gen_data.py — Converts the source data files (vulnerabilities.csv, profiles.json,
gold_set.csv) into app/data.js as embedded JS constants for the offline /
static-host fallback.

Run from project root:
    python tools/gen_data.py
"""
import csv
import json
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(BASE, "data")
APP = os.path.join(BASE, "app")

SNAPSHOT_DATE = "2025-11-01"

PRODUCT_ALIASES = {
    "apache": "Apache HTTP Server",
    "apache httpd": "Apache HTTP Server",
    "apache http server": "Apache HTTP Server",
    "core banking framework": "Core Banking Framework",
    "core banking": "Core Banking Framework",
    "identity provider saas": "Identity Provider SaaS",
    "identity provider": "Identity Provider SaaS",
    "idp": "Identity Provider SaaS",
    "cloud database engine": "Cloud Database Engine",
    "cloud db": "Cloud Database Engine",
    "database engine": "Cloud Database Engine",
    "web application firewall": "Web Application Firewall",
    "waf": "Web Application Firewall",
    "embedded iot gateway": "Embedded IoT Gateway",
    "iot gateway": "Embedded IoT Gateway",
    "enterprise router os": "Enterprise Router OS",
    "router os": "Enterprise Router OS",
    "enterprise router": "Enterprise Router OS",
}


def js_str(s: str) -> str:
    return json.dumps(str(s))


def norm_product(name):
    if not name:
        return ""
    return PRODUCT_ALIASES.get(str(name).strip().lower(), str(name).strip().lower())


def nvd_url(cve_id):
    return f"https://nvd.nist.gov/vuln/detail/{cve_id}"


def load_vulns():
    vulns = []
    with open(os.path.join(DATA, "vulnerabilities.csv"), newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            vulns.append({
                "cve_id": row["cve_id"].strip(),
                "product": row["product_name"].strip(),
                "cvss": float(row["cvss_base_score"]),
                "kev": row["cisa_kev"].strip().lower() == "true",
                "epss": float(row["first_epss"]),
            })
    return vulns


def load_profiles():
    with open(os.path.join(DATA, "profiles.json"), encoding="utf-8") as f:
        return json.load(f)["organizations"]


def load_gold():
    gold = []
    with open(os.path.join(DATA, "gold_set.csv"), newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            gold.append({
                "cve_id": row["cve_id"].strip(),
                "product": row["product_name"].strip(),
                "cvss": float(row["cvss_base_score"]),
                "kev": row["cisa_kev"].strip().lower() == "true",
                "epss": float(row["first_epss"]),
                "rank_bank": int(row["practitioner_rank_bank"]),
                "rank_startup": int(row["practitioner_rank_startup"]),
            })
    return gold


def build():
    vulns = load_vulns()
    profiles = load_profiles()
    gold = load_gold()

    lines = []
    lines.append("/* Auto-generated by tools/gen_data.py — DO NOT EDIT BY HAND.")
    lines.append("   Regenerate with: python tools/gen_data.py")
    lines.append("   Source: data/vulnerabilities.csv, data/profiles.json, data/gold_set.csv */")
    lines.append("")
    lines.append("// Vulnerability records (offline fallback). Snapshot " + SNAPSHOT_DATE)
    lines.append("window.VULNERABILITIES = " + json.dumps(vulns) + ";")
    lines.append("")
    lines.append("// Organisation profiles: alias-aware matching + exposure/importance signals")
    lines.append("window.ORGANIZATIONS = " + json.dumps(profiles, indent=2) + ";")
    lines.append("")
    lines.append("// Gold-set validation records: 5 CVEs with practitioner ranks")
    lines.append("window.GOLD_SET = " + json.dumps(gold) + ";")
    lines.append("")
    lines.append("// Documented alias table (mirrors server.py PRODUCT_ALIASES)")
    lines.append("window.PRODUCT_ALIASES = " + json.dumps(PRODUCT_ALIASES) + ";")
    lines.append("window.SNAPSHOT_DATE = " + js_str(SNAPSHOT_DATE) + ";")
    lines.append("")

    os.makedirs(APP, exist_ok=True)
    out_path = os.path.join(APP, "data.js")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Wrote {out_path}")
    print(f"  vulnerabilities: {len(vulns)}")
    print(f"  organizations:  {len(profiles)}")
    print(f"  gold records:   {len(gold)}")


if __name__ == "__main__":
    build()
